# === Connexion MySQL ===
db.host=localhost
db.port=3306
db.name=ls_motors
db.user=root
db.password=

# === Schéma (BDD fournie) ===
table.user=utilisateur
col.user.id=ID
col.user.nom=Nom
col.user.prenom=Prenom
col.user.email=Email
col.user.mdp=Passwrd
col.user.role=Role
col.user.discord=DiscordPseudo

table.categorie=categorie
col.categorie.id=ID
col.categorie.libelle=Libelle

table.marque=marque
col.marque.id=ID
col.marque.libelle=Nom

table.vehicule=vehicule
col.vehicule.id=ID
col.vehicule.nom=NomModele
col.vehicule.prix=PrixCatalogue
col.vehicule.idmarque=ID_Marque
col.vehicule.idcategorie=ID_Categorie

table.vente=vente
col.vente.id=ID
col.vente.date=DateVente
col.vente.total=PrixVente
col.vente.id_employe=ID_Employe

# === Config marge (%) (1 seule ligne ID=1) ===
table.config=config
col.config.id=ID
col.config.valeur=MargePourcent
config.row.id=1
config.marge.default=40
